import turtle
wn=turtle.Screen()
t1=turtle.Turtle()
def saveTracks():
    tracks=list()
    t1.speed(10)
    t1.penup()
    t1.goto(-400,300)
    t1.right(90)
    tracks.append(t1.pos())
    t1.fd(400)
    tracks.append(t1.pos())
    t1.backward(150)
    tracks.append(t1.pos())
    t1.left(90)
    t1.fd(300)
    tracks.append(t1.pos())
    t1.left(90)
    t1.fd(300)
    tracks.append(t1.pos())
    t1.back(150)
    tracks.append(t1.pos())
    t1.right(90)
    t1.fd(300)
    tracks.append(t1.pos())
    t1.left(90)
    t1.right(90)
    t1.right(90)
    t1.fd(200)
    tracks.append(t1.pos())
    t1.fd(300)
    tracks.append(t1.pos())
    t1.back(100)
    tracks.append(t1.pos())
    t1.left(90)
    t1.fd(200)
    tracks.append(t1.pos())
    return tracks
def replayTracks(mytracks):
    t1.goto(-400,300)
    t1.pendown()
    for i in range(0,len(mytracks)):
        t1.goto(mytracks[i])
def lab7():
    mytracks=saveTracks()
    replayTracks(mytracks)
def main():
    lab7()

main()
